# Generated by Django 5.1.3 on 2024-12-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='following',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_image',
            new_name='profile_picture',
        ),
    ]
