# Generated by Django 5.1.2 on 2024-12-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_post_new_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='new_tags',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
